version: '3.8'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testdb
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=testdb
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
